[package]
name = "invex-server"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
extism = "1.9.0"
rocket = { version = "0.5.1", features = ["serde_json", "uuid", "json", "tls", "secrets"] }
sea-orm = { version = "1.1.1", features = ["sqlx-sqlite", "sqlx-postgres", "macros", "runtime-tokio-rustls", "with-chrono", "with-json", "with-uuid"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
uuid = { version = "1.11.0", features = ["serde", "v4", "fast-rng"] }
