[package]
name = "invex-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["serde_json", "uuid", "json", "tls"] }
rocket_db_pools = { version = "0.2.0", features = ["mongodb"] }
