[default]
address = "0.0.0.0"
port = 8081
secret_key = "WuNALsM2E+xy7OMXn16LQK6K7DdpJjObJz9wmoSp56Q="

[default.databases.invex]
url = "mongodb://invex:invex@localhost:27017/invex"

[default.tls]
certs = "certs/cert.pem"
key = "certs/key.pem"