[default]
address = "0.0.0.0"
port = 8081
secret_key = "WuNALsM2E+xy7OMXn16LQK6K7DdpJjObJz9wmoSp56Q="
log_level = "normal"

[default.limits]
data-form = "1GB"
file = "1GB"

[default.tls]
certs = "certs/cert.pem"
key = "certs/key.pem"

[default.app]
session_duration = "96h"

[default.app.admin]
username = "admin"
email = "admin@example.com"
password = "admin"

[default.app.database]
database = "invex"
connection = "mongodb://invex:invex@localhost:27017/"

[default.app.customization]
server_name = "Test Server"
server_welcome = "I'm gonna getcha"
