[package]
name = "invex-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_builder = "0.20.2"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_repr = "0.1.19"
